---
name: PMVNGPickaxe
version: 1.0
api: 4.0.0
main: DavidGlitch04\PMVNGPickaxe\Pickaxe
src-namespace-prefix: DavidGlitch04\PMVNGPickaxe
author: PMVNG
authors: [DavidGlitch04]
website: https://github.com/PMVNG
...
